---
algorithm:
    type:           GP
    generations:    1000
    stop_fitness:   -2E-16

dataset:
    type: numeric
    file: data/benchmark/nguyen10.in
    test: data/benchmark/nguyen10.in

variables:
    size: 2
    names:
        - x
        - y

fitness:
    type: RMSECostFunction

crossover:
    type: SubtreeCrossoverOperator
    prob: 0.5

mutation:
    type: SubtreeMutationOperator
    prob: 0.55

reproduction:
    type: ReproductionOperator
    prob: 0.05

selection:
    type: TournamentSelection
    tournament_size: 10

population:
    type:   Solution
    size:   500
    initial:
        generator:  RampedHalfInitializer
        size:       500
        min_depth:  2
        max_depth:  6

tree:
    max_depth:      30
    max_node_count: 100
...
