---
algorithm:
    type:           GP
    generations:    1000
    stop_fitness:   -2E-16

dataset:
    type: numeric
    file: data/benchmark/nguyen6.in
    test: data/benchmark/nguyen6.in

variables:
    size: 1
    names:
        - x

fitness:
    type: RMSECostFunction

crossover:
    type: SubtreeCrossoverOperator
    prob: 0.7

mutation:
    type: SubtreeMutationOperator
    prob: 0.25

reproduction:
    type: ReproductionOperator
    prob: 0.05

selection:
    type: TournamentSelection
    tournament_size: 10

population:
    type:   Solution
    size:   1000
    initial:
        generator:  RampedHalfInitializer
        size:       1000
        min_depth:  2
        max_depth:  6

tree:
    max_depth:      10
    max_node_count: 20
...
