---
algorithm:
    type:           GSGP
    generations:    2000
    stop_fitness:   -9E-16

dataset:
    type: numeric
    file: data/benchmark/nguyen10.in
    test: data/benchmark/nguyen10.in

variables:
    size: 2
    names:
        - x
        - y

fitness:
    type: RMSECostFunction

crossover:
    type: SGXE
    prob: 0.

mutation:
    type: SGMR
    prob: 1.

reproduction:
    type: SemanticReproductionOperator
    prob: 0.

selection:
    type: SemanticTournamentSelection
    tournament_size: 10

population:
    size:   500
    initial:
        generator:  SemanticRampedHalfInitializer
        size:       500
        min_depth:  2
        max_depth:  6

tree:
    max_depth:      10
    max_node_count: 15
...
