---
algorithm:
    type:           GP
    generations:    500
    stop_fitness:   -0.0001

dataset:
    type: numeric
    file: data/iris.data
    test: data/iris.data

variables:
    size: 4
    names:
        - a
        - b
        - c
        - d

fitness:
    type: RMSECostFunction

crossover:
    type: SubtreeCrossoverOperator
    prob: 0.8

mutation:
    type: SubtreeMutationOperator
    prob: 0.15

reproduction:
    type: ReproductionOperator
    prob: 0.05

selection:
    type: TournamentSelection
    tournament_size: 10

population:
    type:   Solution
    size:   300
    initial:
        generator:  RampedHalfInitializer
        size:       300
        min_depth:  2
        max_depth:  6

tree:
    max_depth:      20
    max_node_count: 50
...
