---
algorithm:
    type:           GSGP
    generations:    500
    stop_fitness:   0.

dataset:
    type: boolean
    file: data/benchmark/par5.in
    test: data/benchmark/par5.in

variables:
    size: 5
    names:
        - a
        - b
        - c
        - d
        - e

fitness:
    type: BooleanCostFunction

crossover:
    type: SGXB
    prob: 0.9

mutation:
    type: SGMB
    prob: 0.08

reproduction:
    type: SemanticReproductionOperator
    prob: 0.02

selection:
    type: SemanticTournamentSelection
    tournament_size: 10

population:
    size:   1000
    initial:
        generator:  SemanticRampedHalfInitializer
        size:       1000
        min_depth:  2
        max_depth:  6

tree:
    max_depth:      10
    max_node_count: 15
...
