---
algorithm:
    type:           GP
    generations:    1000
    stop_fitness:   0.

dataset:
    type: boolean
    file: data/benchmark/par6.in
    test: data/benchmark/par6.in

variables:
    size: 6
    names:
        - a
        - b
        - c
        - d
        - e
        - f

fitness:
    type: BooleanCostFunction

crossover:
    type: SubtreeCrossoverOperator
    prob: 0.5

mutation:
    type: SubtreeMutationOperator
    prob: 0.5

reproduction:
    type: ReproductionOperator
    prob: 0.

selection:
    type: TournamentSelection
    tournament_size: 10

population:
    type:   Solution
    size:   500
    initial:
        generator:  RampedHalfInitializer
        size:       500
        min_depth:  2
        max_depth:  6

tree:
    max_depth:      30
    max_node_count: 200
...
